export enum CardDetailsActions {
    GET_CARD_DETAILS_REQUEST = 'GET_CARD_DETAILS_REQUEST',
    GET_CARD_DETAILS_SUCCESS = 'GET_CARD_DETAILS_SUCCESS',
    GET_CARD_DETAILS_FAILURE = 'GET_CARD_DETAILS_FAILURE',
    OPEN_CARD_DETAILS = 'OPEN_CARD_DETAILS'
}
