export enum ViewActions {
    GET_MONEY_REQUEST = 'GET_MONEY_REQUEST',
    DATA_RECIEVED_SUCCESSFULLY = 'DATA_RECIEVED_SUCCESSFULLY',
    OPEN_EDITOR = 'OPEN_EDITOR',
    REMOVE_CARD_REQUEST = 'REMOVE_CARD_REQUEST',
    GET_MONEY_BY_CONTINENT_REQUEST = 'GET_MONEY_BY_CONTINENT_REQUEST',
    SET_MONEY_TYPE = 'SET_MONEY_TYPE',
    SET_CONTINENT = 'SET_CONTINENT'
}
